### ISSUE TITLE
Could not find a declaration file for module 'nestjs-trpc'. 

### ISSUE THREAD

**Issue by yamcodes** [KevinEdry/nestjs-trpc#19]
**Edit: I solved the issue by setting `"module"` to `"NodeNext"` as the official TypeScript documentation suggests: https://www.typescriptlang.org/tsconfig/#module. We should add a section about this in the docs and modify the field in `examples/`, thoughts @KevinEdry?**

Hey, thanks for this awesome library!

When following the installation guide with a fresh project, the following `ts` error is shown when using the package:

```
Could not find a declaration file for module 'nestjs-trpc'. '%path%/node_modules/nestjs-trpc/dist/index.js' implicitly has an 'any' type.
  There are types at '%path%/node_modules/nestjs-trpc/dist/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.ts(7016)
```

I tried changing the `tsconfig.json`'s `moduleResolution` as per the suggestion, but that throws another error, requiring the `module` to be changed from `"commonjs"`.

I'm not sure what's the best way to proceed, but either way we should update the documentation with this information because autocomplete for typing does not work on a fresh install of a NestJS project as it is.

**Comment by KevinEdry** [comment]
Thanks for opening an issue an letting me know! I will try replicate this issue and solve it.
It should work on a fresh install of `nestjs`.

**Comment by KevinEdry** [comment]
I think there was a mismatch between the package json "types" section and where the actual types were located. I've updated it locally and will test to ensure things are working properly.

I'll keep you posted!

**Comment by KevinEdry** [comment]
@yamcodes I want to reproduce it, how did you create the fresh project?

**Comment by KevinEdry** [comment]
I assume it was fixed, feel free to open the issue again if it still persists.
