### ISSUE TITLE
Release patch to fix typings?

### ISSUE THREAD

**Issue by NickBolles** [KevinEdry/nestjs-trpc#2]
Hey @KevinEdry I'm looking to try out this package. I found it after reading through this thread: https://github.com/trpc/trpc/discussions/1504 and searching NPM for nest trpc. 

Right now I'm seeing an issue with the typings not mapping. Looks like you've already fixed this in this commit: https://github.com/trpc/trpc/discussions/1504

Can you bump the package to release that change?

Also, I highly suggest posting on that thread (https://github.com/trpc/trpc/discussions/1504) to advertise this package, it looks like it's exactly what everyone there wants.

**Comment by KevinEdry** [comment]
Hey @NickBolles, Thanks for opening an issue! 
This package is about ready to be published, but there are some issues with the monorepo that I need to address. Thats why I haven't published it yet.

I will try and find some time to update everything tomorrow so you can start tinker with it.
I'd love to hear your feedback!

**Comment by KevinEdry** [comment]
Hey @NickBolles, sorry it took a week (work gets in the way of our hobbies sometime).
I got the monorepo and the package to a good working condition with version 1.3.0.
https://www.npmjs.com/package/nestjs-trpc

Try it out, i'd love to get your feedback on it!
