### ISSUE TITLE
Installation instructions show wrong package. `trpc-nestjs` should be `nestjs-trpc`

### ISSUE THREAD

**Issue by Craig1f** [KevinEdry/nestjs-trpc#23]

**Comment by KevinEdry** [comment]
Thanks for bringing this to my attention, a fix will go out shortly.

**Comment by KevinEdry** [comment]
@Craig1f can you direct me to where you found that error?

**Comment by KevinEdry** [comment]
I search the whole repo and can't find it in the code so I'm closing this issue, it was written wrong a week ago and I've changed it prior to you opening the issue so I assume that was it.
If you still find a typo in the docs, feel free to open the issue, i'll be more than happy fix it!
