### ISSUE TITLE
request: Use custom param decorator

### ISSUE THREAD

**Issue by yar2001** [KevinEdry/nestjs-trpc#24]
Hi, really excited to find this powerful library. I plan to migrate to trpc from GraphQL. Is it possible to use `createParamDecorator` or something similar to get custom param decorators?

```ts
import { createParamDecorator, ExecutionContext } from '@nestjs/common';

export const UserDecorator = createParamDecorator((data: unknown, context: ExecutionContext): User => {
  // some logic to get data from context
  return ctx.user;
});
```

To achieve this:
```ts
@Router()
export class AppRouter {
  constructor() {}

  @Query({ output: z.array(someSchema) })
  async test(@UserDecorator() user: User) {
    return [{ _id: user._id }];
  }
}
```

**Comment by KevinEdry** [comment]
Hey @yar2001,
Thanks for taking the time and opening an issue!
I actually never tried it, I think it will works but I don't really know since I had to build a custom implementation for the router in order to get everything to work.

**Comment by yar2001** [comment]
Thanks for your reply! I didn't realize it would be so complicated. Anyway, the current library is good enough for production use.

For anyone who wants custom params, you can generate them in context and write code like this:
```ts
@Router()
export class AppRouter {
  constructor() {}

  @Query({ output: z.array(someSchema) })
  async test(@ctx() { user }: { user: User }) {
    return [{ _id: user._id }];
  }
}
```
