### ISSUE TITLE
Potential Bug: Windows FileScanner adds a slash infront of drive

### ISSUE THREAD

**Issue by kevin-johne** [KevinEdry/nestjs-trpc#28]
Hey, 
thank you for creating this adaptation to NestJs. 
I'm on Windows and had an issue starting this setup I found out from some debugging that a slash is added in front of the drive for example `C:/code/...` -> `/C:/code/...`. This will lead to the error that the file can't be found.

https://github.com/KevinEdry/nestjs-trpc/blob/032c32dc682f18b68e1f811874bc387a5e007c4b/packages/nestjs-trpc/lib/scanners/file.scanner.ts#L34C3-L43C4
```
private normalizePath(p: string): string {
    let pathName = path.resolve(p.replace(/\\/g, '/'));

    // Windows drive letter must be prefixed with a slash
    if (pathName[0] !== '/') {
      pathName = `/${pathName}`;
    }

    return pathName;
  }
```

This behaviour is there for a reason, and would like why, removing it seems to work fine, no errors.

**Comment by KevinEdry** [comment]
Hey Kevin, I took some good practices when working on windows, but I don't work on windows myself so I couldn't test it.
Since you did most of the investigation work, do you want to create a PR to fix this behavior?

**Comment by KevinEdry** [comment]
Solved in `v1.5.2`, please confirm before closing the issue.
🔗 https://github.com/KevinEdry/nestjs-trpc/releases/tag/1.5.2
🔗 https://www.npmjs.com/package/nestjs-trpc

**Comment by kevin-johne** [comment]
Thank you Kevin for the fix, that works for me!
I was planning to change it tomorrow.

**Comment by KevinEdry** [comment]
Yeah I wasn't planning on implementing it myself and let you do it, but another ticket popped up with the same issue.
