### ISSUE TITLE
Error: Unable to Access Root Module File in TRPC Generator

### ISSUE THREAD

**Issue by johnny-y-wang** [KevinEdry/nestjs-trpc#31]
This is the same issue as #29, except the root cause is when the following option is set in `tsconfig.json`

```json
{
  "compilerOptions": {
    "sourceRoot": "/"
  }
}
```

For our specific use case, `sourceRoot` is set to improve issue grouping in Sentry as per Sentry's recommendation. We were able to workaround it by moving this specific compiler option to production build `tsconfig.json`. You might want to call this out in your documentation.

**Comment by KevinEdry** [comment]
Is this specifically from windows? I might write an implementation that will test both instances and will give you the first one it finds.

**Comment by KevinEdry** [comment]
I see, I'll implement a fix tomorrow for this issue, I have a couple of ideas on how to implement something more generalized.

**Comment by KevinEdry** [comment]
Hey @johnny-y-wang, can you share a repo with a reproduction of this behavior? I've tried to repreduce this locally in one of the examples folders within this repository and couldn't get it to fail.

**Comment by KevinEdry** [comment]
> Hey @KevinEdry, I also couldn't reproduce this with an example repo. We have a rather complex monorepo structure, so replicating it 1:1 in a new sample repo is not simple.
> 
> Let's close this for now until/unless someone else runs into this and finds this issue? :)

That makes sense, sorry that I couldn't make your use-case work, the issue is mainly how we figure out your file structure, we do it from the sourcemaps tsc or any other bundler/compiler generates.
If you look at the source map, it should point me to the original `.ts` file, if it doesn't there is not way for the adapter to generate the AppRouter types.
