### ISSUE TITLE
How to generate server types without running dev command

### ISSUE THREAD

**Issue by Mnigos** [KevinEdry/nestjs-trpc#4]

**Comment by KevinEdry** [comment]
I haven't added it because I assumed you will source control the server types, any suggestions on what an alternative for that might look like?

**Comment by Mnigos** [comment]
I suggest to add cli command to generate this types. I'm using this with turborepo and I have two apps api - nestjs app and web - nextjs app. I'm importing types inside nextjs app from nestjs `server.ts` file

**Comment by KevinEdry** [comment]
Thats doable, invoking the type generation is trivial, I'll try to get to it.

**Comment by KevinEdry** [comment]
I couldn't find a cli command for the `nestjs/graphql` adapter which makes me think it might be okay just saving the server.ts to source control and using that in production. 
Can you try that instead?

**Comment by Mnigos** [comment]
> I couldn't find a cli command for the `nestjs/graphql` adapter which makes me think it might be okay just saving the server.ts to source control and using that in production. Can you try that instead?

That's because graphql doesn't need to generate types. Usually the types are generated inside frontend app. I can run the dev command every time I make a change but it's highly inefficient. I would love to automate this with generate command that can run on CI/CD or even in git hook that's called after commit.

**Comment by Mnigos** [comment]
The other possible solution for that is to generate types with `build` command.

**Comment by Mnigos** [comment]
I want to emphasize that I'm ok with keeping generated files in source control(I my opinion any generated files should not be included in source control and especially the dynamic ones, but this is not the reason of my issue). I just want to generate this types other way than running the dev command.

**Comment by KevinEdry** [comment]
Hey, just wanted to give a quick update.
Because I need your AppModule context to generate the types, its not as straight forward as invoking the CLI command, I am still working on a solution but it will take more time than I originally estimated.

**Comment by Mnigos** [comment]
Sure, I'm aware that this might not be the top priority, but I'm glad you're working on solution.

**Comment by KevinEdry** [comment]
Im labeling this as won't fix.
I can't really make a cli command that will generate your types since we are heavily coupled to your nestjs server running to do so.
I use the `@Router` decorator to figure out where your router files are declared, and without your server actually running and applying those decorators, I can't reach those files.

For now I think the best option is to use your dev server to generate the appRouter.

**Comment by Mnigos** [comment]
@KevinEdry Maybe create a script that launches nestjs application and then terminates the task after types are generated?

**Comment by KevinEdry** [comment]
As a module, I don't have access to your AppModule, but how your suggestion is different than just running the server?

**Comment by Mnigos** [comment]
> As a module, I don't have access to your AppModule, but how your suggestion is different than just running the server?

I just want to have some way to generate this types in git hook or CI.
