### ISSUE TITLE
generated types are not resolved correctly when using methods like `pick`

### ISSUE THREAD

**Issue by Mnigos** [KevinEdry/nestjs-trpc#5]
`user.schema.ts`

```ts
export const userSchema = z.object({
  id: z.string(),
  name: z.string(),
  createdAt: z.date(),
})

export const createUserSchema = userSchema.pick({ name: true })
```

`user.router.ts`
```ts
@Router({ alias: 'user' })
export class UsersRouter {
  constructor(private readonly prisma: PrismaService) {}

  @Query({ input: createUserSchema, output: userSchema })
  async login(@Input('name') name: string) {
    const foundUser = await this.prisma.user.findUnique({
      where: {
        name,
      },
    })

    if (foundUser) return foundUser

    return this.prisma.user.create({
      data: {
        name,
      },
    })
  }

  @Query({ input: z.string(), output: userSchema })
  async byName(@Input() name: string) {
    const foundUser = await this.prisma.user.findUnique({
      where: {
        name,
      },
    })

    if (!foundUser) throw new TRPCError({ code: 'NOT_FOUND' })

    return foundUser
  }
}
```

<img width="605" alt="Screenshot 2024-09-27 at 12 16 30" src="https://github.com/user-attachments/assets/6c09d33a-34e8-48b9-a3c3-50f6f579ef69">

**Comment by KevinEdry** [comment]
Thanks for opening this issue with so much details, im on it!

**Comment by KevinEdry** [comment]
So the expected behavior is that it should flatten the userSchema to
``` typescript
z.object({
  id: z.string(),
  name: z.string(),
  createdAt: z.date()}).pick...
```

Which isn't happening, I'm still checking to see why.

**Comment by Mnigos** [comment]
> Thanks for opening this issue with so much details, im on it!

Not long ago I was also thinking on creating package like that so I'm really glad that you've created it and that you're contributing to it actively.

**Comment by Mnigos** [comment]
> So the expected behavior is that it should flatten the userSchema to
> 
> ```ts
> z.object({
>   id: z.string(),
>   name: z.string(),
>   createdAt: z.date()}).pick...
> ```
> 
> Which isn't happening, I'm still checking to see why.

exactly

**Comment by Mnigos** [comment]
@KevinEdry Your pr fixes `pick` usage, but when i use nested objects schema it still doesn't resolve correctly.

`thought.schema.ts`
```ts
export const thoughtSchema = z.object({
  id: z.string(),
  content: z.string(),
  author: userSchema,
  createdAt: z.date(),
})
```

<img width="591" alt="Screenshot 2024-09-28 at 19 24 27" src="https://github.com/user-attachments/assets/0c06b48c-5148-4c0c-b1a4-775215d8a224">

**Comment by KevinEdry** [comment]
hmm, it should work for nested, let me push a fix for it.

**Comment by KevinEdry** [comment]
Yup, it seems that when its from a different file, it doesn't work.
The zod schema flattening functionality is the most difficult one to fix and update, but I am on it 👍.

**Comment by KevinEdry** [comment]
The [1.3.2](https://github.com/KevinEdry/nestjs-trpc/releases/tag/1.3.2) release should have fixed this, can you confirm?

**Comment by Mnigos** [comment]
Unfortunately no, I updated `nestjs-trpc` to `1.3.2`, but issue still occurs.

This is repo btw. -> https://github.com/Mnigos/share-your-thought

**Comment by KevinEdry** [comment]
> Unfortunately no, I updated `nestjs-trpc` to `1.3.2`, but issue still occurs.
> 
> This is repo btw. -> https://github.com/Mnigos/share-your-thought

Oh you are using barrel files!
Try importing it from the actual file, skipping the `index.ts` barrel file. I need to think of an elegant solution to deal with barrel files.

**Comment by Mnigos** [comment]
> > Unfortunately no, I updated `nestjs-trpc` to `1.3.2`, but issue still occurs.
> > This is repo btw. -> https://github.com/Mnigos/share-your-thought
> 
> Oh you are using barrel files! Try importing it from the actual file, skipping the `index.ts` barrel file. I need to think of an elegant solution to deal with barrel files.
> 
> The functionality for flattening the `zod` schema takes the current file that it is on, and creates an import map for it (what are you importing from where) and when it wants to flatten the imported schema, it goes to the file you referenced in in the import statement.
> 
> Because you are using barrel files, the import file you specified technically doesn't mention anything about the imported schema.
> 
> I can go on an search every file referenced in the barrel file, but thats highly inefficient 🤔

Not the best solution, but I guess I will have to do it like that for now.

**Comment by KevinEdry** [comment]
@Mnigos the latest release should solve the barrel files issue.

**Comment by KevinEdry** [comment]
It closes the issue automatically, can you confirm that this worked?

**Comment by Mnigos** [comment]
Yes, now it works perfectly!

**Comment by Mnigos** [comment]
> Yes, now it works perfectly!

Or not exactly. I was pretty sure that generated types were resolved correctly, but now I'm running this application and it still contains unresolved `userSchema` inside even without barrel files. I don't know why i thought that this was resolved, maybe vscode just didn't show me the errors and I just took a quick look.

**Comment by KevinEdry** [comment]
Do you have the `"sourceMap": true` option enabled in your tsconfig?

**Comment by Mnigos** [comment]
I didn't, I added it right now, but the issue still exist.

**Comment by Mnigos** [comment]
`thought.schema.ts`
```ts
import { userSchema } from '~/users/user.schema'

export const thoughtSchema = z.object({
  id: z.string(),
  content: z.string(),
  author: userSchema,
  createdAt: z.date(),
})
```

`server.ts`
```ts
import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;

const appRouter = t.router({
  thoughts: t.router({
    all: publicProcedure.output(z.array(z.object({
      id: z.string(),
      content: z.string(),
      author: userSchema,
      createdAt: z.date(),
    }))).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
});
export type AppRouter = typeof appRouter;
```
`tsconfig.json`
```json
{
  "extends": "@repo/typescript-config/nestjs.json",
  "compilerOptions": {
      "esModuleInterop": true,
    "skipLibCheck": true,
    "allowJs": true,
    "target": "ES2022",
    "lib": ["ESNext"],
    "resolveJsonModule": true,
    "moduleDetection": "force",
    "isolatedModules": true,
    "verbatimModuleSyntax": true,

    "strict": true,
    "strictNullChecks": true,
    "strictBindCallApply": false,
    "strictPropertyInitialization": false,
    "noUncheckedIndexedAccess": true,
    "noImplicitAny": true,
    "noImplicitOverride": true,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,

    "declaration": true,
    "declarationMap": true,
    "removeComments": true
  
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "incremental": true,
    "sourceMap": true,
    "outDir": "./dist",
    "types": ["vitest/globals"],
    "paths": {
      "~/*": ["./src/*"]
    }
  },
  "include": ["src"],
  "exclude": ["node_modules", "dist"]
}
```

**Comment by KevinEdry** [comment]
Yeah I don't think I'm handling this case:
```
    "paths": {
      "~/*": ["./src/*"]
    }
```

**Comment by Mnigos** [comment]
> Yeah I don't think I'm handling this case:
> 
> ```
>     "paths": {
>       "~/*": ["./src/*"]
>     }
> ```
> 
> I'm looking at your imports, and if they are obscured by a the tsconfig path I can't resolve them.

You're right it works without path alias. But i would love to use path aliases with this library since they're making my imports more clear. 

Maybe you can add property in `TRPCModule` options to configure custom aliases like this.
```ts
@Module({
  imports: [
    TRPCModule.forRoot({
      autoSchemaFile: '.',
      alias: [
        {
          find: '~',
          replacement: fileURLToPath(new URL('src', import.meta.url)),
        },
      ],
    }),
  ],
})
export class AppModule {}
```
This is how it's done in vitest config.

**Comment by KevinEdry** [comment]
can you open a new issue for this? I will try to get to it.
